language: python
python:
  - "2.7"
  - "3.2"
  - "3.3"

branches:
  except:
    - master

install:
  - "pip install nose"
  - "pip install pbr==0.5.21"
  - "pip install -e ."

script: "python setup.py nosetests"
